### ISSUE TITLE
Broken link for refexp annotations

### ISSUE THREAD

**Issue by changliu19** [dekelio/disclip-open-vocab-reg#1]
Hi dekelio,

Thank you so much for your work on referring expression generation! I just attempted to download the code for DisCLIP, but found the link for refexp expressions (https://chechiklab.biu.ac.il/~brachalior/projects/disclip/data) is broken.

Could you help to repairing the link, or provide some advice on how to generate the data JSONL files? Greatly appreciate your help!

**Comment by dekelio** [comment]
Hi Chang, 
Thanks, [here is a link to Google Drive](https://drive.google.com/file/d/17aU0nGx160AidgLPEVx-dx6QxLNGdFVU/view?usp=sharing) with the files. I'll keep it active until the issue with the original url is fixed.

**Comment by changliu19** [comment]
Great! The code is working now. Many thanks for sharing and for your response!
